invoices/urls.py
from django.urls import path

from invoices import views

app_name = 'Invoices'
urlpatterns = [
    path('create_invoice/<int:client_id>', views.create_invoice, name='create_invoice'),
    path('client_invoices/<int:client_id>', views.client_invoices, name='client_invoices'),
    path('create_client', views.create_client, name='create_client'),
    path('invoice_clients', views.invoice_clients, name='invoice_clients'),
    path('invoice/services/<int:invoice_id>', views.invoice_services, name='invoice_services'),
    path('add_invoice_services/<int:invoice_id>', views.add_invoice_services, name='add_invoice_services'),
    path('invoice/preview/<int:invoice_id>', views.invoice_preview, name='invoice_preview'),
    path('invoice/payments/<int:invoice_id>', views.invoice_payments, name='invoice_payments'),
    path('add/invoice/payment/<int:invoice_id>', views.add_payment, name='add_payment'),
    path('mark/invoice/as/payed/<int:invoice_id>', views.mark_invoice_as_payed, name='mark_invoice_as_payed'),
    path('delete/invoice/service/<int:service_id>', views.delete_service, name='delete_service'),
    path('delete/invoice/<int:invoice_id>', views.delete_invoice, name='delete_invoice'),

    path('edit/invoice/<int:invoice_id>', views.edit_invoice, name='edit_invoice'),
    path('edit/invoice/service/<int:service_id>', views.edit_invoice_service, name='edit_invoice_service'),

    path('edit/client/<int:client_id>', views.edit_client, name='edit_client'),
]

invoices_new/urls.py
from django.urls import path

from invoices import views

app_name = 'Invoices'
urlpatterns = [
    path('create_invoice/<int:client_id>', views.create_invoice, name='create_invoice'),
    path('client_invoices/<int:client_id>', views.client_invoices, name='client_invoices'),
    path('create_client', views.create_client, name='create_client'),
    path('invoice_clients', views.invoice_clients, name='invoice_clients'),
    path('invoice/services/<int:invoice_id>', views.invoice_services, name='invoice_services'),
    path('add_invoice_services/<int:invoice_id>', views.add_invoice_services, name='add_invoice_services'),
    path('invoice/preview/<int:invoice_id>', views.invoice_preview, name='invoice_preview'),
    path('invoice/payments/<int:invoice_id>', views.invoice_payments, name='invoice_payments'),
    path('add/invoice/payment/<int:invoice_id>', views.add_payment, name='add_payment'),
    path('mark/invoice/as/payed/<int:invoice_id>', views.mark_invoice_as_payed, name='mark_invoice_as_payed'),
    path('delete/invoice/service/<int:service_id>', views.delete_service, name='delete_service'),
    path('delete/invoice/<int:invoice_id>', views.delete_invoice, name='delete_invoice'),

    path('edit/invoice/<int:invoice_id>', views.edit_invoice, name='edit_invoice'),
    path('edit/invoice/service/<int:service_id>', views.edit_invoice_service, name='edit_invoice_service'),

    path('edit/client/<int:client_id>', views.edit_client, name='edit_client'),
    path('invoice/filter', views.invoice_filter, name='invoice_filter'),
]

roberms/urls.py
#from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views, views

from roberms import settings

urlpatterns = [
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(
        template_name='r/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='r/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name='r/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='r/password_reset_complete.html'), name='password_reset_complete'),
    # url('^', include('django.contrib.auth.urls')),


 #   url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('roberms/super/admin/', admin.site.urls),

    path('', include('sms.urls')),
   # path('water/', include('water.urls')),
    path('sms/v1/', include('sms_api.urls')),
    path('roberms/admin/', include('roberms_admin.urls')),
    path('roberms/salesperson/', include('salesperson.urls')),
    path('invoices/', include('invoices.urls')),
    path('api/v1/', include('mpesa_api.urls')),
    path('school/', include('school.urls')),
    path('shortcode/', include('shortcode.urls')),
    path('adda/', include('adda.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sms/urls.py
    path('login', views.roberms_login, name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('verify/account', views.verify_account, name='verify_account'),
    path('', views.home, name='sms-home'),
    path('profile', views.profile, name='profile'),
    path('about', views.about, name='about'),
    
    path('services', views.services, name='services'),
    path('contact', views.contact, name='contact'),

   path('edit/water/station/<int:network_id>', views.edit_water_network, name='edit_water_network'),
    path('apps', views.apps, name='apps'),
    path('home', views.water_apps, name='water_apps'),
    path('main/meter', views.main_meter, name='main_meter'),
    path('main/water/refill', views.main_water_refill, name='main_water_refill'),
    path('main/meter/chart', views.main_meterchart, name='main_meterchart'),
    path('client/dashboard/<int:client_id>', views.client_dashboard, name='client_dashboard'),
    path('send/', views.send, name='send'),
    path('send/plain', views.send_to_plain, name='send_to_plain'),
    path('simple/sms', views.simple_sms, name='simple_sms'),
    path('simple/sms/resend/<int:message_id>', views.simple_sms_resend, name='simple_sms_resend'),
    path('simple/disconnection/reminder/<int:client_id>', views.disconnection_reminder, name='disconnection_reminder'),
    path('simple/sms/preview', views.simple_sms_preview, name='simple_sms_preview'),
    path('import/csv', views.import_csv_2, name='import_csv'),
    path('import/readings/csv', views.import_readings_csv, name='import_readings_csv'),
    path('merge', views.merge_sms_2, name='merge_sms'),
    path('confirm', views.confirm, name='confirm'),
    path('customer/reports/<int:tracking_code>', views.reports, name='customer_reports'),
    path('water/sms/reports/<int:tracking_code>', views.water_sms_reports, name='water_sms_reports'),
    path('customer/credit', views.customer_credit, name='customer_credit'),
    path('customer/contacts', views.customer_contacts, name='customer_contacts'),
    path('water/clients', views.water_clients, name='water_clients'),
    path('water/clients/<int:court_id>', views.water_clients_court, name='water_clients_court'),
    path('water/payments', views.water_payments, name='water_payments'),
    path('water/expenses', views.water_expenses, name='water_expenses'),
    path('add/water/expense', views.water_manual_expenses, name='water_manual_expenses'),
    path('water/payments/<int:client_id>', views.water_payments_clients, name='water_payments_clients'),
    path('water/expenses/<int:category_id>', views.water_expense_category, name='water_expense_category'),
    path('water/sub/accounts/<int:main_id>', views.water_subaccounts_allocations, name='water_subaccounts_allocations'),
    path('water/payments/manual', views.water_manual_payments, name='water_manual_payments'),
    path('water/payments/allocations', views.water_payments_allocations, name='water_payments_allocations'),
    path('water/courts', views.water_courts, name='water_courts'),
    #path('water/courts/network', views.water_courts_network, name='water_courts_network'),
    path('create/water/network', views.create_water_network, name='create_water_network'),
    path('edit/client/<int:client_id>', views.edit_water_client, name='edit_water_client'),
    path('invoice/preview/<int:invoice_id>', views.invoice_preview, name='invoice_preview'),
    path('bill/preview/<int:invoice_id>', views.bill_preview, name='bill_preview'),
    path('statement/preview/<int:client_id>', views.statement_preview, name='statement_preview'),
    
    path('edit/sysconf/<int:client_id>', views.edit_sys_config, name='edit_sys_config'),
    path('client/invoices/<int:client_id>', views.client_invoices, name='client_invoices'),
    path('client/bills/<int:client_id>', views.client_bills, name='client_bills'),
    #path('client_invoices/<int:client_id>', views.client_invoices, name='client_invoices'),
    path('meter/readings', views.meter_readings, name='meter_readings'),
    path('main/readings', views.main_readings, name='main_readings'),
    path('bills/sent', views.bills_sent, name='bills_sent'),
    path('meter/readings/<int:client_id>', views.meter_readings_clients, name='meter_readings_clients'),
    path('bills/sent/<int:client_id>', views.bills_sent_clients, name='bills_sent_clients'),
    path('add/meter', views.add_meter, name='add_meter'),
    path('add/meter/readings', views.add_meter_readings, name='add_meter_readings'),
    path('add/main/readings', views.add_main_readings, name='add_main_readings'),
    path('add/fines', views.add_fines, name='add_fines'),
    #path('meter/readings/report/<int:report_value>', views.meter_readings_report, name='meter_readings_report'),
    #path('meter/readings/report', views.meter_readings_report, name='meter_readings_report'),
    #path('meter/readings/report', views.meter_readings_report, name='meter_readings_report'),
    path('meter/replace', views.meter_replacement, name='meter_replacement'),
    path('main/meter/replace', views.main_meter_replacement, name='main_meter_replacement'),
    path('water/sysconfig', views.water_system_config, name='water_system_config'),
    path('water/config/history', views.water_config_history, name='water_config_history'),
    path('customer/comprehensive/reports', views.comprehensive_reports, name='comprehensive_reports'),
    path('water/reports', views.meter_readings_report, name='meter_readings_report'),
    path('multisearch', views.multi_search, name='multi_search'),
    path('statement/date', views.statement_date, name='statement_date'),
    
    #path('water/reports', views.water_reports, name='water_reports'),
    #path('water/reports', views.meter_readings_report, name='meter_readings_report'),
    #path('meter/readings/report/<int:report_value>', views.meter_readings_report, name='meter_readings_report'),
    path('sent/report/details/<str:track_code>', views.report_details, name='report_details'),
    path('generate/sms/report/<str:track_code>', views.generate_sms_report, name='generate_sms_report'),
    path('add/meter/upload/', views.add_meter_upload, name='add_meter_upload'),
    path('add/fine/upload', views.add_fine_upload, name='add_fine_upload'),
    path('personalized/sms/menu', views.personalized_sms_menu, name='personalized_sms_menu'),
    path('personalized/contacts', views.personalized_from_contact_list, name='personalized_contacts'),
    path('send/all', views.send_to_all, name='send_to_all'),
    path('send/to/court', views.send_to_court, name='send_to_court'),
    path('send/to/network', views.send_to_network, name='send_to_network'),
    # path('choose/contact/personalized/contactsgroups', views.choose_contact_groups, name='choose_contact_groups'),
    path('contact/list/sample/merged', views.c_sample_merged, name='c_sample_merged'),
    path('messages/dashboard', views.messages_dashboard, name='messages_dashboard'),

    # groups
    path('create/group', views.create_group, name='create_group'),
    path('group/contacts/<int:group_id>', views.group_contacts, name='group_contacts'),
    path('water/courts/network/<int:network_id>', views.water_courts_network, name='water_courts_network'),
    path('create/group/contact/<int:group_id>', views.create_contact, name='create_group_contact'),
    path('create/court/network/<int:network_id>', views.create_court, name='create_network_court'),
    path('import/group/contacts/<int:group_id>', views.import_contacts, name='import_contacts'),
    path('import/water/clients', views.import_water_clients, name='import_water_clients'),
    path('import/water/clients/<int:client_id>', views.import_water_sub_clients, name='import_water_sub_clients'),
    path('delete/group/<int:group_id>', views.delete_group, name='delete_group'),
    path('monthly/credit/usage', views.credit_used, name='credit_usage'),
    path('delete/contacts/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('update/group/<int:group_id>', views.update_group, name='update_group'),
    path('update/network/<int:network_id>', views.update_network, name='update_network'),
    path('update/contact/<int:contact_id>', views.update_contact, name='update_contact'),
    # path('delete/contact/<int:g')

    path('simple', views.SendSmsView.as_view(), name='sms-simple'),
    path('smsreport', views.SmsReportView.as_view(), name='sms-simple'),
    path('water/revenues', views.water_revenues, name='water_revenues'),
    path('sms/reports', views.sms_reports, name='my_sms_reports'),
    path('water/sent/sms', views.water_sent_sms, name='water_sent_sms'),
    path('water/sent/sms/<str:client_phone>', views.water_sent_sms_client, name='water_sent_sms_client'),
    # path('send/sms', views.send_sms, name='send_sms'),
    # path('get/sms/delivery/status', views.get_delivery_status, name='get_delivery_status'),

    #top up
    path('payment/verification', views.verify_payment, name='verify_payment'),
    path('register', views.register, name='register'),
    path('edit/profile', views.edit_profile, name='edit_profile'),

    # till_numbers
    path('till/numbers', views.customer_till_numbers, name='customer_till_numbers'),
    path('add/till/number', views.add_till_number, name='add_till_number'),
    path('edit/till/number/<int:till_number_id>', views.edit_till_number, name='edit_till_number'),
    path('delete/till/number/<int:till_number_id>', views.delete_till_number, name='delete_till_number'),

    #contacts
    path('activate/deactivate/contact/<int:contact_id>', views.activate_deactivate_contact, name='activate_deactivate_contact'),

    #celery
    path('contacts/upload/status/<str:task_id>', views.contacts_upload_status, name='contacts_upload_status' ),
    path('meter/reading/upload/status/<str:task_id>', views.meter_reading_upload_status, name='meter_reading_upload_status' ),

invoices/models.py
from django.db import models

# Create your models here.


class Client(models.Model):
    company_name = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=250)
    client_number = models.CharField(max_length=250)
    address = models.CharField(max_length=250)
    location = models.CharField(max_length=250)
    kra_pin = models.CharField(max_length=250, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Client'
        verbose_name_plural = 'Clients'


class Invoice(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    invoice_date = models.CharField(max_length=250)
    invoice_number = models.CharField(max_length=250, null=True)
    discount = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    status_complete = models.BooleanField(default=False)
    vat = models.IntegerField(default=16)

    class Meta:
        verbose_name = 'Invoice'
        verbose_name_plural = 'Invoices'


class Service(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    service = models.TextField()
    unit_price = models.CharField(max_length=250)
    quantity = models.CharField(max_length=250)


class Payments(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    amount = models.CharField(max_length=250)

    class Meta:
        verbose_name = 'Payment'
        verbose_name_plural = 'Payments'

invoices_new/templates/invoices/add_invoice_payment.html
{% extends 'admin_layouts/new_base.html' %}
{% load static %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="row">
<div class="col-sm-3">

</div>
<div class="col-sm-6">
    <div class="tile">
        <form action="{% url 'Invoices:add_payment' invoice.id %}" method="post">
    {% csrf_token %}

    <div class="form-group">
        <label>Amount</label>
        <input type="text" name="amount" class="form-control">
    </div>
            <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>

</div>

</div>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

invoices_new/templates/invoices/add_invoice_service.html
{% extends 'admin_layouts/new_base.html' %}
{% load static %}

{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="row">
<div class="col-sm-3">

</div>
<div class="col-sm-6">
    <div class="tile">
        <h4>Add Invoice Service</h4>
        <hr>
        <form action="{% url 'Invoices:add_invoice_services' invoice.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>Service</label>
                <input type="text" name="service" class="form-control">
            </div>

            <div class="form-group">
                <label>Unit Price</label>
                <input type="text" name="unit_price" class="form-control">
            </div>

            <div class="form-group">
                <label>Quantity</label>
                <input type="number" name="quantity" class="form-control">
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>
</div>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

invoices_new/templates/invoices/client_invoices.html
{% extends 'admin_layouts/new_base.html' %}
{% load static %}

{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <div class="row">
        <div class="col-md-6">
            <h4>Client Invoices</h4>
        </div>
        <div class="col-sm-6">
            <a href="{% url 'Invoices:create_invoice' client.id %}" class="btn btn-outline-primary pull-right">New Invoice</a>
    </div>
    </div>
</div>
        <div class="tile-body">
            <table class="table table-hover table-bordered" id="sampleTable">
                <thead>
                <tr>
                    <th>Company Name</th>
                    <th>Invoice Creation Date</th>
                    <th>Invoice Date</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for invoice in invoices %}
                <tr>
                    <td><a href="{% url 'Invoices:invoice_services' invoice.id %}">{{ invoice.client.company_name }}</a></td>
                    <td>{{ invoice.created_at|date:'Y/m/d' }}</td>
                    <td>{{ invoice.invoice_date }}</td>
                    <td>
                        {% if invoice.status_complete == True %}
                            Paid
                            {% else %}
                            Pending
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'Invoices:edit_invoice' invoice.id %}" title="Edit" class="btn btn-outline-primary btn-sm"><i class="fa fa-edit fa-lg"></i></a>
                        <a href="#" id="demoSwal" title="Delete" class="btn btn-outline-danger btn-sm"><i class="fa fa-trash-o"></i></a>
                        <div hidden>
                            <a href="{% url 'Invoices:delete_invoice' invoice.id%}" id="invoice_delete"></a>
                        </div>
                        <a href="{% url 'Invoices:invoice_preview' invoice.id %}" title="" class="btn btn-outline-primary btn-sm">Invoice Preview</a>
                        <a href="{% url 'Invoices:invoice_payments' invoice.id %}" class="btn btn-outline-primary btn-sm" >Payments</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block additional_scripts %}
    <script type="text/javascript" src="{% static 'js/bootstrap-notify.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/sweetalert.min.js' %}"></script>
    <script type="text/javascript">
          $('#demoSwal').click(function(){
            swal({
                title: "Are you sure?",
                text: "You will not be able to recover this invoice or the services under it",
                type: "warning",
                showCancelButton: true,
                confirmButtonText: "Yes, delete it!",
                cancelButtonText: "No, cancel please!",
                closeOnConfirm: false,
                closeOnCancel: false
            }, function(isConfirm) {
                if (isConfirm) {
                    document.getElementById('invoice_delete').click();
                    swal("Deleted!", "Invoice deletion complete", "success");
                } else {
                    swal("Cancelled", "Invoice deletion cancelled:)", "error");
                }
            });
          });
    </script>
{% endblock %}

invoices_new/templates/invoices/invoice_clients.html
{% extends 'admin_layouts/new_base.html' %}
{% load static %}

{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <div class="row">
        <div class="col-sm-6">
            <h4>Clients</h4>
        </div>
        <div class="col-sm-6">
            <a href="{% url 'Invoices:create_client' %}" class="btn btn-outline-primary pull-right">New Client</a>
        </div>
    </div>
    <hr>
</div>
        <div class="tile-body">
            <table class="table table-hover table-bordered" id="sampleTable">
                <thead>
                <tr>
                    <th>Company Name</th>
                    <th>Phone Number</th>
                    <th>Customer Number</th>
                    <th>KRA PIN</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for client in clients %}
                <tr>
                    <td><a href="{% url 'Invoices:client_invoices' client.id %}">{{ client.company_name }}</a></td>
                    <td>{{ client.phone_number }}</td>
                    <td>{{ client.client_number }}</td>
                    <td>{{ client.kra_pin }}</td>
                    <td>
                        <a href="{% url 'Invoices:edit_client' client.id %}" title="Edit" class="btn btn-outline-primary btn-sm"><i class="fa fa-edit fa-lg"></i></a>
{#                        <a href="" title="Approve" class="btn btn-outline-primary btn-sm"><i class="fa fa-check-square-o"></i></a>#}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

invoices_new/templates/invoices/invoice_filter.html
{% extends 'admin_layouts/new_base.html' %}
{% load static %}

{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <div class="row">
        <div class="col-md-6">
            <h4>Invoice Filter</h4>
        </div>
        <div class="col-sm-6">

        </div>
    </div>

    <hr>
    <form action="{% url 'Invoices:invoice_filter' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-sm-4">
                <input type="date" class="form-control" name="from_date" value="{{ from_date }}" required>
            </div>

            <div class="col-sm-4">
                <input type="date" class="form-control" name="to_date" value="{{ to_date }}" required>
            </div>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-outline-success">Filter</button>
            </div>
        </div>
    </form>
    <hr>

</div>
        <div class="tile-body">
            <table class="table table-hover table-bordered" id="sampleTable">
                <thead>
                <tr>
                    <th>Company Name</th>
                    <th>Invoice Creation Date</th>
                    <th>Invoice Date</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for invoice in invoices %}
                <tr>
                    <td><a href="{% url 'Invoices:invoice_services' invoice.id %}">{{ invoice.client.company_name }}</a></td>
                    <td>{{ invoice.created_at }}</td>
                    <td>{{ invoice.invoice_date }}</td>
                    <td>
                        {% if invoice.status_complete == True %}
                            Paid
                            {% else %}
                            Pending
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'Invoices:edit_invoice' invoice.id %}" title="Edit" class="btn btn-outline-primary btn-sm"><i class="fa fa-edit fa-lg"></i></a>
                        <a href="#" id="demoSwal" title="Delete" class="btn btn-outline-danger btn-sm"><i class="fa fa-trash-o"></i></a>
                        <a href="{% url 'Invoices:invoice_preview' invoice.id %}" title="" class="btn btn-outline-primary btn-sm">Invoice Preview</a>
                        <a href="{% url 'Invoices:invoice_payments' invoice.id %}" class="btn btn-outline-primary btn-sm" >Payments</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

invoices_new/templates/invoices/invoice_payments.html
{% extends 'admin_layouts/new_base.html' %}
{% load static %}

{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <div class="row">
        <div class="col-sm-6">
            <h4>Invoice Payments</h4>
        </div>
        <div class="col-sm-6">
            <a href="{% url 'Invoices:add_payment' invoice.id %}" class="btn btn-outline-primary pull-right">Add Payment</a>
            <a href="{% url 'Invoices:mark_invoice_as_payed'  invoice.id %}" class="btn btn-outline-primary pull-right">Mark As Payed</a>
        </div>
    </div>
    <hr>
</div>
        <div class="tile-body">
            <table class="table table-hover table-bordered" id="sampleTable">
                <thead>
                <tr>
                    <th>Company Name</th>
                    <th>Amount</th>
                </tr>
                </thead>
                <tbody>
                {% for payment in payments %}
                <tr>
                    <td>{{ payment.invoice.client.company_name }}</td>
                    <td>{{ payment.amount }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block additional_scripts %}

{% endblock %}

invoices_new/templates/invoices/invoice_services.html
{% extends 'admin_layouts/new_base.html' %}
{% load static %}

{% block additional_meta %}

{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}
<div class="tile">
<div class="tile-title">
    <div class="row">
        <div class="col-md-6">
            <h4>Invoice Services</h4>
        </div>
        <div class="col-sm-6">
            <a href="{% url 'Invoices:add_invoice_services' invoice.id %}" class="btn btn-outline-primary pull-right">New Invoice Service</a>
    </div>
    </div>
</div>
        <div class="tile-body">
            <table class="table table-hover table-bordered" id="sampleTable">
                <thead>
                <tr>
                    <th>Service</th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for service in services %}
                <tr>
                    <td><a>{{ service.service }}</a></td>
                    <td>{{ service.unit_price }}</td>
                    <td>{{ service.quantity }}</td>
                    <td>
                        <a href="{% url 'Invoices:edit_invoice_service' service.id %}" title="Edit" class="btn btn-outline-primary btn-sm"><i class="fa fa-edit fa-lg"></i></a>
                        <a href="#" id="deleteService" title="Delete" class="btn btn-outline-danger btn-sm"><i class="fa fa-trash-o"></i></a>
                        <div hidden>
                            <a href="{% url 'Invoices:delete_service' service.id %}" id="service_delete"></a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block additional_scripts %}
 <script type="text/javascript" src="{% static 'js/bootstrap-notify.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/sweetalert.min.js' %}"></script>
<script type="text/javascript">
      $('#deleteService').click(function(){
      	swal({
      		title: "Are you sure?",
      		text: "You will not be able to recover this invoice service",
      		type: "warning",
      		showCancelButton: true,
      		confirmButtonText: "Yes, delete it!",
      		cancelButtonText: "No, cancel please!",
      		closeOnConfirm: false,
      		closeOnCancel: false
      	}, function(isConfirm) {
      		if (isConfirm) {
      		    document.getElementById('service_delete').click();
      			swal("Deleted!", "Service Deleted Successfully", "success");
      		} else {
      			swal("Cancelled", "Deletion cancelled :)", "error");
      		}
      	});
      });
    </script>
{% endblock %}